### ISSUE TITLE
Issue during a test

### ISSUE THREAD

**Issue by Nusky173** [TuxML/tuxml-kci#2]
During a test with that command : "_python3 tuxml_kci.py --config tinyconfig --kernel_version 4.13.3_" or any other version. I had a little crash with an error message that told me : "go to the build file of the kernel version and run make oldconfig". What I have done and run again the same command I mention earlier.

And i had a lot of choice for my configuration. 

It was something like that : "Compile the kernel with debug info (DEBUG_INFO) [N/y/?] (NEW)" i had to choose between Y or No i guess, to enable or disable this option .

or something like that : 

" 1: option 1 
2: option 2 
3: option 3
choose between the few option above"

I've done that until the end and i had no crash, no error, the script have suceed. 

My guess was : ok i just choose some option for my config. And this could happen again even if I don't use tinyconfig as the config file but defconfig also or randomconfig.

**Comment by FAMILIAR-project** [comment]
Thanks! How did you get this error? 
What's the command you used? 

You should document how to reproduce your issue, otherwise it's hard to understand and investigate.

**Comment by acherm** [comment]
we can close this issue (hypothesis: the .config was for x86_32 arch, not x86_64 as expected and kci tries to fix the .config with a kconfig `--sync` stuff, that requires to adresse a number of questions 
now the script is working

**Comment by bibi14010** [comment]
This step is no longer usefull, as kernelci already do it while executing build_kernel. See [build.py](https://github.com/kernelci/kernelci-core/blob/f90c60690fb12a2cb4c0fb0542c6c0f85641fc9c/kernelci/build.py#L1336)

**EDIT :**
The same type of issue appen while trying to reuse our own .config file
